name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run commnds
      run: pwd
    
    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

    - name: Build Artifact
      run: .mvn package