name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run commnds
      run: pwd
      working-directory: ./demo/
    
    - name: Build with Maven
      run: mvn clean install
      working-directory: ./demo

    - name: Run Tests
      run: mvn test
      working-directory: ./demo

    - name: Build Artifact
      run: mvn package
      working-directory: ./demo

    - name: Run commnds
      run: ls
      working-directory: ./demo/target

    - uses: jfrog/setup-jfrog-cli@v3
      env:
        # JFrog platform url (for example: https://acme.jfrog.io) 
        JF_URL: ${{ secrets.JF_URL }}
        
        # Basic authentication credentials
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        #or
        # JFrog Platform access token
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - run: |
        jf rt ping
        jfrog rt upload \
            <path-to-jar-file> \
            <jfrog-repository>/<path-to-upload>